---
abstract: 'oEmbed consumer'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-oEmbed
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  Filter::Util::Call: 0
  HTML::Element: 0
  JSON::XS: 0
  LWP: 0
  XML::LibXML::Simple: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
